### ISSUE TITLE
Uncaught TypeError: Cannot read property 'content' of null

### ISSUE THREAD

**Issue by alphilippo** [ConandSherry/vue-template-beautify#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 ia32
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Famille
**Thrown From**: [vue-template-beautify](https://github.com/ConandSherry/vue-template-beautify) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'content' of null

```
At C:\Users\AL\.atom\packages\vue-template-beautify\lib\vue-template-beautify.js:80

TypeError: Cannot read property 'content' of null
    at Object.beautify (/packages/vue-template-beautify/lib/vue-template-beautify.js:80:36)
    at HTMLElement.vueTemplateBeautifyToggle (/packages/vue-template-beautify/lib/vue-template-beautify.js:26:60)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1227580)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1223714)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -0:10.7.0 intentions:highlight (input.hidden-input)
     -0:10.4.0 vue-template-beautify:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-django 0.3.2 
atom-live-server 2.3.0 
atom-react-alt-templates 0.6.0 
atom-smart-template 0.3.2 
atom-template-engine 0.2.2 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
create-github-repo 1.1.2 
django-templates 0.5.0 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.26 
file-templates 0.2.0 
github-notifications 0.1.2 
github-plus 1.0.0 
github-utils 1.6.0 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.14.0 
html-template-generator 0.3.0 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
materialize-css 0.5.1 
mdl-snippets 0.3.0 
my-github-profile 0.2.1 
template-generator 0.16.0 
vue-template-beautify 0.1.2 
```

**Comment by ConandSherry** [comment]
can you provide your file contents,i guess there is no template tag like this`<template></template>` in your file content

**Comment by Tsaukpaetra** [comment]
Can concur, I accidentally tried to format a just-js file and was lead here.
